name: Deploy Doc

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: npm intall, build
        run: |
          npm i
          npm run build
        env:
          CI: true

      - name: copy doc site
        run: mkdir doc-sites && cp -rif ./{components,docs,libs,index.html,index.js,README.md,LICENSE} doc-sites
        env:
          CI: true

      - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@github.com:nomui/nomui.github.io.git
        BRANCH: main
        FOLDER: doc-sites
        SSH_PRIVATE_KEY: ${{ secrets.GITHUB_TOKEN }}
        KNOWN_HOSTS_FILE: resources/known_hosts # Path relative to the root of the repository
